/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "secondary": "#5d5f5f",
        "inverse-on-surface": "#f0f1f1",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#1b1b1b",
        "on-secondary-fixed-variant": "#454747",
        "inverse-surface": "#2f3131",
        "surface-bright": "#f9f9f9",
        "on-background": "#1a1c1c",
        "outline-variant": "#cfc4c5",
        "on-primary-fixed-variant": "#474747",
        "on-tertiary-fixed-variant": "#474747",
        "surface-tint": "#5e5e5e",
        "primary-container": "#1b1b1b",
        "on-secondary-container": "#5f6161",
        "surface-container": "#eeeeee",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#848484",
        "on-surface-variant": "#4c4546",
        "surface-container-high": "#e8e8e8",
        "inverse-primary": "#c6c6c6",
        "outline": "#7e7576",
        "surface-variant": "#e2e2e2",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-container": "#848484",
        "on-secondary-fixed": "#1a1c1c",
        "tertiary": "#000000",
        "error": "#ba1a1a",
        "secondary-container": "#dcdddd",
        "background": "#f9f9f9",
        "secondary-fixed-dim": "#c6c6c7",
        "tertiary-container": "#1b1b1b",
        "on-error": "#ffffff",
        "surface-container-highest": "#e2e2e2",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary": "#ffffff",
        "surface": "#f9f9f9",
        "primary-fixed-dim": "#c6c6c6",
        "surface-dim": "#dadada",
        "on-surface": "#1a1c1c",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f3f4",
        "tertiary-fixed-dim": "#c6c6c6",
        "primary-fixed": "#e2e2e2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "sheet": "16px"
      },
      spacing: {
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1280px",
        "stack-md": "32px",
        "gutter": "24px",
        "stack-sm": "16px",
        "stack-xl": "80px"
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "button-text": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "letterSpacing": "0.03em", "fontWeight": "400" }],
        "button-text": ["14px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}

